name: Build WDA for iOS 26
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_17.app
      - name: Build WebDriverAgent
        run: |
          xcodebuild build-for-testing \
            -project WebDriverAgent.xcodeproj \
            -scheme WebDriverAgentRunner \
            -destination 'generic/platform=iOS' \
            -derivedDataPath ./build
      - name: Package to IPA
        run: |
          mkdir -p Payload
          cp -r ./build/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app Payload/
          zip -r WebDriverAgent.ipa Payload
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WDA-IPA-File
          path: WebDriverAgent.ipa
